server:
  port: 8082

spring:
  application:
    name: mercado-x-email
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mercado_x}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: email-service-group
    listener:
      missing-topics-fatal: false
whatsapp:
  api:
    base-url: ${WHATSAPP_API_BASE_URL:https://graph.facebook.com/v20.0/mock-phone-id}
    token: ${WHATSAPP_API_TOKEN:mock-token}
    graph-base-url: ${WHATSAPP_GRAPH_BASE_URL:https://graph.facebook.com/v20.0}
    verify-token: ${WHATSAPP_VERIFY_TOKEN:placeholder-verify-token}
    app-secret: ${WHATSAPP_APP_SECRET:placeholder-app-secret}

kafka:
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION:file:./secrets/public.pem}


